/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sd.com.br.gui.ambiente.prefeitura;

import clientesemmaven.Conexoes;
import edu.ifpb.dac.Funcionario;
import edu.ifpb.dac.Prefeitura;
import ifpb.dac.service.DAOIT;
import ifpb.dac.service.FuncionarioServiceIT;
import ifpb.dac.service.PrefeituraServiceIT;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sergiod
 */
public class NovoFuncionario extends javax.swing.JPanel {

    /**
     * Creates new form NovoFuncionario
     */
    
    private Prefeitura prefeitura;
    
    public NovoFuncionario(Prefeitura prefeitura) {
        this.prefeitura = prefeitura;
        initComponents();
        init();
    }
    
    public void init(){
        
        jPDadosCompletos.setVisible(false);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTCPF = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jPDadosCompletos = new javax.swing.JPanel();
        jLMsgNaoCadastrado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTEmail = new javax.swing.JTextField();
        jLSenha = new javax.swing.JLabel();
        jTSenha = new javax.swing.JTextField();
        jBCadastrar = new javax.swing.JButton();
        jBVincular = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Novo Funcionario");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("CPF");

        jTCPF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTCPF.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBBuscar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jPDadosCompletos.setBackground(new java.awt.Color(255, 255, 255));

        jLMsgNaoCadastrado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLMsgNaoCadastrado.setForeground(new java.awt.Color(255, 0, 0));
        jLMsgNaoCadastrado.setText("Funcionario não cadastrado. Complete o cadastro para vincula-lo a sua prefeitura.");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Nome");

        jTNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTNome.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Email");

        jTEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTEmail.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLSenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLSenha.setText("Senha");

        jTSenha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTSenha.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBCadastrar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBCadastrar.setText("Cadastrar");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        jBVincular.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBVincular.setText("Vincular");
        jBVincular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVincularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPDadosCompletosLayout = new javax.swing.GroupLayout(jPDadosCompletos);
        jPDadosCompletos.setLayout(jPDadosCompletosLayout);
        jPDadosCompletosLayout.setHorizontalGroup(
            jPDadosCompletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDadosCompletosLayout.createSequentialGroup()
                .addGroup(jPDadosCompletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLMsgNaoCadastrado)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLSenha))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jTNome)
            .addComponent(jTEmail)
            .addComponent(jTSenha)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDadosCompletosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPDadosCompletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBCadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBVincular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPDadosCompletosLayout.setVerticalGroup(
            jPDadosCompletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDadosCompletosLayout.createSequentialGroup()
                .addComponent(jLMsgNaoCadastrado)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBVincular, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPDadosCompletos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jLabel1))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jTCPF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPDadosCompletos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        // TODO add your handling code here:
        
        
        
        if(jTCPF.getText().length() > 0){
            FuncionarioServiceIT fs = Conexoes.funcionarioService();
            
            Funcionario f = fs.buscarPorCPF(jTCPF.getText());
            
            if(f != null){
                jPDadosCompletos.setVisible(true);
                jLMsgNaoCadastrado.setVisible(false);
                jTSenha.setVisible(false);
                jLSenha.setVisible(false);
                
                jTNome.setText(f.getNome());
                jTEmail.setText(f.getEmail());
                
                jTNome.setEditable(false);
                jTEmail.setEditable(false);
                
                jBVincular.setVisible(true);
                jBCadastrar.setVisible(false);
                
                
            } else {
                jPDadosCompletos.setVisible(true);
                jLMsgNaoCadastrado.setVisible(true);
                jTSenha.setVisible(true);
                jLSenha.setVisible(true);
                
                jTNome.setText("");
                jTEmail.setText("");
                
                jTNome.setEditable(true);
                jTEmail.setEditable(true);
                
                jBCadastrar.setVisible(true);
                jBVincular.setVisible(false);
                
            }
            
            
        }else{
            JOptionPane.showMessageDialog(jPanel1, "Preencha todos os campos corretamente!");
        }
        
        revalidate();
        repaint();
        
        
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        // TODO add your handling code here:
        
        
        if((jTCPF.getText().length() > 0) && (jTNome.getText().length() > 0) && (jTEmail.getText().length() > 0) &&
                (jTSenha.getText().length() > 0)){
            
            DAOIT dao = Conexoes.DAO();
            PrefeituraServiceIT ps = Conexoes.prefeituraService();
            Funcionario f = new Funcionario(jTNome.getText(), jTCPF.getText(), jTEmail.getText(), jTSenha.getText());
            
            dao.salvar(f);
            
            String resultado = ps.cadastrarNaPrefeitura(prefeitura, f);
            JOptionPane.showMessageDialog(jPanel1, resultado);
            
            
        } else {
            JOptionPane.showMessageDialog(jPanel1, "Preencha todos os campos corretamente!");
        }
        
    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void jBVincularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVincularActionPerformed
        // TODO add your handling code here:
         
            if(jTCPF.getText().length() > 0){
                
                FuncionarioServiceIT fs = Conexoes.funcionarioService();
                PrefeituraServiceIT ps = Conexoes.prefeituraService();
                
                Funcionario f = fs.buscarPorCPF(jTCPF.getText());
                
                String resultado = ps.vincular(prefeitura, f);
                JOptionPane.showMessageDialog(jPanel1, resultado);   
                
            } else {
                JOptionPane.showMessageDialog(jPanel1, "Preencha todos os campos corretamente!");   
            }
            
            
        
        
        
    }//GEN-LAST:event_jBVincularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBVincular;
    private javax.swing.JLabel jLMsgNaoCadastrado;
    private javax.swing.JLabel jLSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPDadosCompletos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTCPF;
    private javax.swing.JTextField jTEmail;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTextField jTSenha;
    // End of variables declaration//GEN-END:variables
}
