/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sd.com.br.gui.ambiente.admin;

import clientesemmaven.Conexoes;
import edu.ifpb.dac.Prefeitura;
import ifpb.dac.service.PrefeituraServiceIT;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import sd.com.br.gui.ModeloTabela;

/**
 *
 * @author SergioD
 */
public class SolicitacoesPendentes extends javax.swing.JPanel {

    /**
     * Creates new form SolicitacoesPendentes
     */
    public SolicitacoesPendentes() {
        initComponents();
        init();
    }
    
    
    public void init(){
        
        PrefeituraServiceIT ps = Conexoes.prefeituraService();
        List<Prefeitura> prefeituras = ps.prefeiturasPendentes();
        
        if(prefeituras != null){
            jPTabela.setVisible(true);
            ArrayList dados = new ArrayList();
            String[] colunas = new String[]{"Nome", "Cidade", "Estado", "Codigo"};
            
            for(int i = 0 ; i < prefeituras.size() ; i++){
                dados.add(new Object[]{
                                        prefeituras.get(i).getNome(),
                                        prefeituras.get(i).getCidade().getCidadePK().getNomeCidade(),
                                        prefeituras.get(i).getCidade().getCidadePK().getSiglaEstado(),
                                        prefeituras.get(i).getId()
                                      });
            }
            
            ModeloTabela tabela = new ModeloTabela(dados, colunas);
            jTable1.setModel(tabela);
            jTable1.setRowHeight(40);
            jTable1.getTableHeader().setReorderingAllowed(false);            
            
            
        } else {
            jPTabela.setVisible(false);
            JOptionPane.showMessageDialog(jPanel1, "Não foi Encontrado nenhum resultado!");
        }
        
        revalidate();
        repaint();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPTabela = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Solicitações Pendentes");

        jPTabela.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPTabelaLayout = new javax.swing.GroupLayout(jPTabela);
        jPTabela.setLayout(jPTabelaLayout);
        jPTabelaLayout.setHorizontalGroup(
            jPTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPTabelaLayout.setVerticalGroup(
            jPTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTabelaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPTabela;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
