/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sd.com.br.gui.ambiente.funcionario;

import clientesemmaven.Conexoes;
import edu.ifpb.dac.Cidade;
import edu.ifpb.dac.Denuncia;
import edu.ifpb.dac.EstadoDeAcompanhamento;
import ifpb.dac.service.DenunciaServiceIT;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;


/**
 *
 * @author SergioD
 */
public class AtualizarDenuncia extends javax.swing.JPanel {

    /**
     * Creates new form AtualizarDenuncia
     */
    
    private int codigoDenuncia;
    private Cidade cidade;
    
    public AtualizarDenuncia(Cidade cidade) {
        this.cidade = cidade;
        initComponents();
        init();
    }

    public void init(){
        jPMsgNaoEncontrado.setVisible(false);
        jPDadosDaDenuncia.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTCodigo = new javax.swing.JTextField();
        jBPesquisar = new javax.swing.JButton();
        jPMsgNaoEncontrado = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPDadosDaDenuncia = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTRua = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTBairro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTNumero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTDescricao = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jCSituacao = new javax.swing.JComboBox();
        jBAtualizar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Acompanhar Denuncia");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Codigo");

        jTCodigo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTCodigo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBPesquisar.setText("Pesquisar");
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });

        jPMsgNaoEncontrado.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Denuncia não encontrada");

        javax.swing.GroupLayout jPMsgNaoEncontradoLayout = new javax.swing.GroupLayout(jPMsgNaoEncontrado);
        jPMsgNaoEncontrado.setLayout(jPMsgNaoEncontradoLayout);
        jPMsgNaoEncontradoLayout.setHorizontalGroup(
            jPMsgNaoEncontradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMsgNaoEncontradoLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 365, Short.MAX_VALUE))
        );
        jPMsgNaoEncontradoLayout.setVerticalGroup(
            jPMsgNaoEncontradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMsgNaoEncontradoLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPDadosDaDenuncia.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Rua");

        jTRua.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTRua.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Bairro");

        jTBairro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTBairro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Numero");

        jTNumero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTNumero.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Descricao");

        jTDescricao.setColumns(20);
        jTDescricao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTDescricao.setRows(5);
        jTDescricao.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportView(jTDescricao);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Situação");

        jCSituacao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCSituacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AGUARDANDO", "ATENDIDA", "EM_TRABALHO" }));

        jBAtualizar.setText("Atualizar");
        jBAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPDadosDaDenunciaLayout = new javax.swing.GroupLayout(jPDadosDaDenuncia);
        jPDadosDaDenuncia.setLayout(jPDadosDaDenunciaLayout);
        jPDadosDaDenunciaLayout.setHorizontalGroup(
            jPDadosDaDenunciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTRua)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDadosDaDenunciaLayout.createSequentialGroup()
                .addGroup(jPDadosDaDenunciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jTBairro))
                .addGap(18, 18, 18)
                .addGroup(jPDadosDaDenunciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPDadosDaDenunciaLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(147, 147, 147))
                    .addComponent(jTNumero)))
            .addComponent(jScrollPane1)
            .addGroup(jPDadosDaDenunciaLayout.createSequentialGroup()
                .addGroup(jPDadosDaDenunciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jCSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 247, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDadosDaDenunciaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPDadosDaDenunciaLayout.setVerticalGroup(
            jPDadosDaDenunciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDadosDaDenunciaLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTRua, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPDadosDaDenunciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDadosDaDenunciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jBPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jPMsgNaoEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jPDadosDaDenuncia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jLabel1))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jPMsgNaoEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPDadosDaDenuncia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        // TODO add your handling code here:
        
        if (jTCodigo.getText().length() > 0){
            
            DenunciaServiceIT ds = Conexoes.denunciaService();
            
            int codigo = -1;
            
            try {
                codigo = Integer.parseInt(jTCodigo.getText());                
            } catch (Exception e) {}
            
            
            Denuncia d = ds.pesquisarPorCodigo(codigo, cidade);

            if (d != null){
                codigoDenuncia = d.getId();
                jPMsgNaoEncontrado.setVisible(false);
                jPDadosDaDenuncia.setVisible(true);
                
                jTRua.setText(d.getEnderecoDenuncia().getRua());
                jTBairro.setText(d.getEnderecoDenuncia().getBairro());
                jTNumero.setText(Integer.toString(d.getEnderecoDenuncia().getNumero()));
                jTDescricao.setText(d.getDescricao());
                
                jTRua.setEditable(false);
                jTBairro.setEditable(false);
                jTNumero.setEditable(false);
                jTDescricao.setEditable(false);
                
                if(d.getEstadoDeAcompanhamento() == EstadoDeAcompanhamento.AGUARDANDO){
                    jCSituacao.setSelectedIndex(0);
                } else if(d.getEstadoDeAcompanhamento() == EstadoDeAcompanhamento.ATENDIDA){
                    jCSituacao.setSelectedIndex(1);
                } else if(d.getEstadoDeAcompanhamento() == EstadoDeAcompanhamento.EM_TRABALHO){
                    jCSituacao.setSelectedIndex(2);
                } else {
                    jCSituacao.setSelectedIndex(-1);
                }
                
                
                
            }else{
                jPMsgNaoEncontrado.setVisible(true);
                jPDadosDaDenuncia.setVisible(false);
            }
            
            
            revalidate();
            repaint();
            

            
        }else{
            JOptionPane.showMessageDialog(jPanel1, "Preencha todos os campos corretamente!");
        }
        
        
        
    }//GEN-LAST:event_jBPesquisarActionPerformed

    private void jBAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtualizarActionPerformed
        // TODO add your handling code here:
        
        
            String item = (String) jCSituacao.getSelectedItem();
            EstadoDeAcompanhamento estadoDeAcompanhamento = null;

            if (item == "AGUARDANDO"){
                estadoDeAcompanhamento = EstadoDeAcompanhamento.AGUARDANDO;
            } else if(item == "ATENDIDA"){
                estadoDeAcompanhamento = EstadoDeAcompanhamento.ATENDIDA;
            } else if(item == "EM_TRABALHO"){
                estadoDeAcompanhamento = EstadoDeAcompanhamento.EM_TRABALHO;
            }            
            

            DenunciaServiceIT ds = Conexoes.denunciaService();
            String resultado = ds.atualizarAcompanhamento(codigoDenuncia, estadoDeAcompanhamento, cidade);                
            
            JOptionPane.showMessageDialog(jPanel1, resultado);
            
        
    }//GEN-LAST:event_jBAtualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtualizar;
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JComboBox jCSituacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPDadosDaDenuncia;
    private javax.swing.JPanel jPMsgNaoEncontrado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTBairro;
    private javax.swing.JTextField jTCodigo;
    private javax.swing.JTextArea jTDescricao;
    private javax.swing.JTextField jTNumero;
    private javax.swing.JTextField jTRua;
    // End of variables declaration//GEN-END:variables
}
